// Testing image creation for game.
// Body needs to contain minimum two colors, maximum four colors.
// Returns if successful object including created image.

POST http://localhost:5000/api/images/create
Content-Type: application/json

{
    "colors": [
        "#252525",
        "#161616",
        "#363636",
        "#545454"
    ]
}